/// Flutter icons IconosPersonolizados
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconosPersonolizados
///      fonts:
///       - asset: fonts/IconosPersonolizados.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///
import 'package:flutter/widgets.dart';

class IconosPersonalizados {
  IconosPersonalizados._();

  static const _kFontFam = 'IconosPersonolizados';
  static const _kFontPkg = null;

  static const IconData location = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_circled = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out_map = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_1 = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_return = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_tab = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_voice = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vpn_key = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_2 = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_right = const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_up = const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_backspace = const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_capslock = const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_hide = const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_inv = const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_2 = const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_outline = const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_3 = const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_outline = const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2 = const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight = const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_3 = const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_4 = const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_circled = const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_5 = const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_7 = const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move = const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_1 = const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 = const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_empty = const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_empty = const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarm = const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData police = const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility = const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessible = const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adb = const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_a_photo = const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplanemode_active = const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_1 = const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_color = const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_clear = const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_end = const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_membership = const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_to_action = const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_low = const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_high = const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_1 = const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_2 = const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_3 = const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_4 = const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_5 = const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_outer = const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_right = const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_style = const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_top = const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build = const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer = const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_cut = const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create = const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_queue = const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_new_folder = const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_mac = const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_windows = const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_transit = const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_subway = const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drive_eta = const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_available = const IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = const IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_busy = const IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_note = const IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_seat = const IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_to_app = const IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = const IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData https = const IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_on = const IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_off = const IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset_mic = const IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_grocery_store = const IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last_page = const IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = const IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers_clear = const IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lens = const IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_add = const IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_drink = const IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_taxi = const IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_1 = const IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = const IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData near_me = const IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = const IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = const IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circle_filled = const IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_circle_outline = const IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = const IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = const IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan_tool = const IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = const IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_drop = const IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_arrow = const IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle_filled = const IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = const IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = const IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_very_satisfied = const IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_very_dissatisfied = const IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_satisfied = const IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_2 = const IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_neutral = const IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_dissatisfied = const IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select_all = const IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_feed = const IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = const IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = const IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show_chart = const IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = const IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = const IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = const IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = const IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand = const IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = const IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hand = const IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hand = const IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_big = const IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_big = const IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_big = const IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_big = const IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = const IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = const IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = const IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = const IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir = const IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = const IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir = const IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = const IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled2 = const IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled2 = const IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = const IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = const IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = const IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = const IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = const IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical = const IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal = const IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = const IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = const IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = const IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start_alt = const IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_fw = const IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_bw = const IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject = const IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = const IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = const IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = const IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = const IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = const IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight = const IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right = const IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify = const IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = const IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center = const IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = const IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_width = const IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = const IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer = const IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty_1 = const IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = const IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = const IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = const IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = const IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = const IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = const IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_1 = const IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = const IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guidedog = const IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet = const IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = const IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font = const IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize = const IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = const IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center_1 = const IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left_1 = const IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right_1 = const IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify_1 = const IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideshare = const IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bag = const IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boy_with_pet_lines = const IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_photos = const IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_queue = const IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = const IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_inclusive = const IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData album = const IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistant_photo = const IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = const IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_money = const IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_file = const IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_all = const IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_border = const IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = const IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy = const IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy_1 = const IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = const IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_flat = const IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = const IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_flat_angled = const IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_individual_suite = const IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_extra = const IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplay = const IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = const IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast = const IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casino = const IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiber_manual_record = const IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_library = const IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mode_edit = const IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mms = const IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = const IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add = const IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stay_current_landscape = const IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stay_current_portrait = const IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stay_primary_landscape = const IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stay_primary_portrait = const IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_1 = const IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms = const IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = const IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = const IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap_1 = const IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area = const IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = const IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = const IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = const IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_alt = const IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_1 = const IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_1 = const IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = const IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_alt = const IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_outline = const IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_2 = const IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grain = const IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grade = const IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gradient = const IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_2 = const IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_overscan = const IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner = const IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perm_scan_wifi = const IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = const IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_1 = const IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 = const IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_2 = const IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarms = const IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin6 = const IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin5 = const IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin4 = const IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin3 = const IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin2 = const IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ie = const IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marquee = const IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_angry = const IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_grin = const IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_saint = const IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy = const IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_happy = const IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = const IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass = const IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = const IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = const IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = const IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = const IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large = const IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = const IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = const IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = const IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = const IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 = const IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_1 = const IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled_1 = const IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2_1 = const IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = const IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = const IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = const IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_1 = const IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_2 = const IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = const IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = const IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = const IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_1 = const IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = const IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = const IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = const IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = const IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = const IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = const IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = const IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_1 = const IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = const IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_1 = const IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_1 = const IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = const IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = const IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = const IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar_3 = const IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = const IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_3 = const IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_2 = const IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw = const IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = const IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_ccw = const IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric_outline = const IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric = const IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet_outline = const IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet = const IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors_outline = const IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors = const IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt = const IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitch = const IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData religious_christian = const IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giraffe = const IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf = const IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_1 = const IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData belowground_rail = const IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = const IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = const IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox = const IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buffer = const IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = const IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_circled = const IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone_1 = const IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = const IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = const IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_1 = const IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt = const IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_1 = const IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_1 = const IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = const IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = const IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_3 = const IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_3 = const IconData(0xf047, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_ext = const IconData(0xf08e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_empty = const IconData(0xf096, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate = const IconData(0xf0a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks = const IconData(0xf0ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = const IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_alt = const IconData(0xf0b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker = const IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs = const IconData(0xf0c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_bullet = const IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table = const IconData(0xf0ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = const IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge = const IconData(0xf0e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_empty = const IconData(0xf0e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sitemap = const IconData(0xf0e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = const IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = const IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text = const IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = const IconData(0xf0f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital = const IconData(0xf0f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance = const IconData(0xf0f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medkit = const IconData(0xf0fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter_jet = const IconData(0xf0fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = const IconData(0xf0fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = const IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = const IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = const IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = const IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_empty = const IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner = const IconData(0xf110, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = const IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = const IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown = const IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh = const IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_1 = const IconData(0xf11c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_empty = const IconData(0xf11d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_checkered = const IconData(0xf11e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = const IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = const IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = const IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = const IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_empty = const IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extinguisher = const IconData(0xf134, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_left = const IconData(0xf137, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_right = const IconData(0xf138, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_up = const IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_circled_down = const IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = const IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_squared = const IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_ext_alt = const IconData(0xf14c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_alt = const IconData(0xf14d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = const IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_name_up = const IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_name_down = const IconData(0xf15e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_number_up = const IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = const IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = const IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = const IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = const IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = const IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = const IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = const IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = const IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled2 = const IconData(0xf18e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled2 = const IconData(0xf190, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = const IconData(0xf193, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_squared_alt = const IconData(0xf196, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_cap = const IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = const IconData(0xf1ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_filled = const IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = const IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spoon = const IconData(0xf1b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube = const IconData(0xf1b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cubes = const IconData(0xf1b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cab = const IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = const IconData(0xf1ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = const IconData(0xf1bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = const IconData(0xf1c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = const IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_word = const IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel = const IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_powerpoint = const IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code = const IconData(0xf1c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeopen = const IconData(0xf1cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paragraph = const IconData(0xf1dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_1 = const IconData(0xf1e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = const IconData(0xf1e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binoculars = const IconData(0xf1e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_visa = const IconData(0xf1f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_mastercard = const IconData(0xf1f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_discover = const IconData(0xf1f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_amex = const IconData(0xf1f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_paypal = const IconData(0xf1f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_stripe = const IconData(0xf1f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyedropper = const IconData(0xf1fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = const IconData(0xf1fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday = const IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area_1 = const IconData(0xf1fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_2 = const IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line_1 = const IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off = const IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on = const IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = const IconData(0xf206, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = const IconData(0xf207, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angellist = const IconData(0xf209, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_plus = const IconData(0xf217, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = const IconData(0xf219, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship = const IconData(0xf21a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = const IconData(0xf21c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData street_view = const IconData(0xf21d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server = const IconData(0xf233, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = const IconData(0xf238, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subway = const IconData(0xf239, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = const IconData(0xf23a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_1 = const IconData(0xf251, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_2 = const IconData(0xf252, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_3 = const IconData(0xf253, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = const IconData(0xf254, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus_o = const IconData(0xf271, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_minus_o = const IconData(0xf272, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_times_o = const IconData(0xf273, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check_o = const IconData(0xf274, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin = const IconData(0xf276, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_signs = const IconData(0xf277, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_o = const IconData(0xf278, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = const IconData(0xf279, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = const IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_6 = const IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
